/**
 * Knights and knaves.
 *
 * Generated by picking the answer first: choose who is what, emit a statement
 * for each speaker that is true exactly when they are a knight, then check by
 * brute force that the puzzle those statements make has the intended solution
 * and no other. Building forwards and verifying backwards, with the verifier
 * being the definition of the answer rather than a second procedure.
 */

import { GeneratorContext, buildSeries, extendWithSeries, seriesWanted } from "./context";
import { Question } from "../models/question.models";
import { coinFlip, getRandomSymbols, shuffle } from "../utils/question.utils";
import { canGenerateQuestion, clampPremises } from "../models/settings.models";
import { EnumQuestionType } from "../constants/question.constants";
import { hi, subj } from "../utils/phrasing";
import {
    Claim, KNAVES_NOTE, describeClaim, describeStatement, determined, drawClaims, holds, solve,
} from "../utils/knaves.utils";

export function createKnaves(ctx: GeneratorContext, numOfPremises: number): Question {
    ctx.logger.info("createKnaves");

    const type = EnumQuestionType.Knaves;
    const settings = ctx.settings;

    if (!canGenerateQuestion(type, numOfPremises, settings)) {
        throw new Error("Cannot generate.");
    }

    numOfPremises = clampPremises(type, numOfPremises);

    // One statement per speaker, so premises and speakers are the same count.
    const speakers = Math.max(2, numOfPremises);

    /*
     * Compound claims are earned. "At least one of you two is a knave" cannot
     * be resolved by looking at one speaker, so it turns the puzzle from a
     * chain of implications into a small case analysis — a real step up rather
     * than more of the same.
     */
    const compound = ctx.hasRung(type, "compound");

    /*
     * So is ambiguity. With every puzzle uniquely solvable, "is X a knight?"
     * always has an answer and the reader never has to notice that the
     * statements failed to settle it. The same argument as under-specified
     * composed spaces, and the same wording: a claim holds only if it holds in
     * every consistent reading.
     */
    const allowOpen = ctx.hasRung(type, "undetermined");

    for (let attempt = 0; attempt < 400; attempt++) {
        const names = getRandomSymbols(settings, speakers);
        const world = Array.from({ length: speakers }, () => coinFlip());

        // A puzzle where everyone is the same kind is a puzzle with nothing in
        // it: every statement about kinds is uniformly true or uniformly false.
        if (world.every(w => w === world[0])) continue;

        const claims = drawClaims(world, compound);
        if (!claims) continue;

        const solutions = solve(claims);
        if (!solutions.length) continue;
        if (solutions.length > 1 && !allowOpen) continue;

        const settled = determined(solutions);
        // Something has to be worth asking about, whichever way the item goes.
        if (!allowOpen && settled.size === 0) continue;

        const question = new Question(type);
        question.bucket = [...names];
        question.setup = [KNAVES_NOTE];
        question.premises = shuffle(claims.map((c, i) => describeStatement(i, c, names)));

        if (!fillConclusion(ctx, question, names, claims, solutions, settled, allowOpen)) continue;
        return question;
    }

    throw new Error("Cannot generate.");
}

function fillConclusion(
    ctx: GeneratorContext,
    question: Question,
    names: string[],
    claims: Claim[],
    solutions: boolean[][],
    settled: Map<number, boolean>,
    allowOpen: boolean,
): boolean {
    const n = names.length;

    /*
     * Open items ask about someone the statements do not pin down, and are
     * false whichever type they name. Roughly half the time when the rung is
     * live, so the wording gives nothing away.
     */
    if (allowOpen) {
        const open = [...Array(n).keys()].filter(i => !settled.has(i));
        if (open.length && coinFlip()) {
            const who = open[Math.floor(Math.random() * open.length)];
            const claimed = coinFlip();
            question.conclusion = mustBe(names[who], claimed);
            question.isValid = false;
            question.explanation = [
                `${solutions.length} readings fit everything said.`,
                ...solutions.slice(0, 4).map(s => readingLine(s, names)),
                `so ${subj(names[who])} is not settled either way, and the claim`
                + ` does not have to hold`,
            ];
            return true;
        }
    }

    const options = [...settled.keys()];
    if (!options.length) return false;

    const who = options[Math.floor(Math.random() * options.length)];
    const truth = settled.get(who)!;
    const claimTrue = coinFlip();
    const claimed = claimTrue ? truth : !truth;

    question.conclusion = allowOpen ? mustBe(names[who], claimed) : plainly(names[who], claimed);
    question.isValid = claimTrue;
    question.explanation = explain(names, claims, solutions[0], who, truth);

    /*
     * More people, against the same testimony.
     *
     * Working out who is lying is the whole cost of the item and it is paid
     * once; asking about a second person reads the answer off a reading already
     * arrived at. Only people the statements *settle* — an unsettled one is
     * false whichever type it names, and a series of those would teach that
     * "no" is the percentage answer rather than that some people cannot be
     * placed.
     */
    if (seriesWanted(ctx)) {
        const settledOnes = [...settled.keys()];
        extendWithSeries(question, buildSeries(want => {
            if (settledOnes.length < 2) return null;
            const other = settledOnes[Math.floor(Math.random() * settledOnes.length)];
            const is = settled.get(other)!;
            const says = want ? is : !is;
            return {
                text: allowOpen ? mustBe(names[other], says) : plainly(names[other], says),
                isValid: says === is,
                key: String(other),
            };
        }));
    }
    return true;
}

const plainly = (name: string, knight: boolean) =>
    `${subj(name)} is a ${hi(knight ? "knight" : "knave")}`;

const mustBe = (name: string, knight: boolean) =>
    `It must be true that ${subj(name)} is a ${hi(knight ? "knight" : "knave")}`;

const readingLine = (world: boolean[], names: string[]) =>
    world.map((k, i) => `${subj(names[i])} ${k ? "knight" : "knave"}`).join(", ");

/**
 * The reading that fits, checked statement by statement, then the near miss.
 *
 * Checking the solution is the honest half: every speaker's type has to match
 * the truth of what they said, and reading that off is exactly what the reader
 * is being asked to do. The second half names one speaker whose statement
 * breaks if the queried person is flipped — not a proof that no other reading
 * works, and worded so it does not claim to be, but it is the step that
 * actually decides the answer.
 */
function explain(
    names: string[],
    claims: Claim[],
    world: boolean[],
    who: number,
    truth: boolean,
): string[] {
    const lines = claims.map((c, i) =>
        `${subj(names[i])} is a ${hi(world[i] ? "knight" : "knave")}, and "${describeClaim(c, names)}"`
        + ` is ${hi(holds(c, world) ? "true" : "false")} — which fits.`);

    const flipped = [...world];
    flipped[who] = !flipped[who];
    const breaks = claims.findIndex((c, i) => flipped[i] !== holds(c, flipped));
    if (breaks >= 0) {
        // Naming the same person twice reads as a stutter, and the self-case is
        // the commonest one: a speaker's own claim is usually what pins them.
        lines.push(breaks === who
            ? `Make ${subj(names[who])} the other kind and their own statement stops fitting.`
            : `Make ${subj(names[who])} the other kind and ${subj(names[breaks])}`
              + ` no longer matches what they said.`);
    }

    lines.push(`so ${plainly(names[who], truth)}`);
    return lines;
}
