/**
 * Every test, in one process.
 *
 * Each file registers its cases on import; this file exists so adding a suite
 * is one line and running them is one command.
 */

import { run } from "./harness";

import "./phrasing.test";
import "./ndspace.test";
import "./progression.test";
import "./easy-mode.test";
import "./generators.test";
import "./induction.test";
import "./derivation.test";
import "./fatigue.test";
import "./profiles.test";
import "./keybind.test";
import "./review.test";
import "./feedback.test";
import "./symbols.test";
import "./random-labels.test";
import "./mutual-moves.test";
import "./stream.test";
import "./answering.test";
import "./verdict.test";
import "./difficulty.test";
import "./delay-line.test";
import "./unscored.test";
import "./history-view.test";
import "./practice-choices.test";
import "./stimuli.test";
import "./shape-rotation.test";
import "./customise.test";
import "./history-store.test";
import "./save-data.test";
import "./map.test";
import "./web.test";
import "./coldstart.test";
import "./indeterminacy.test";
import "./transform-match.test";
import "./rungfit.test";
import "./theme-contrast.test";
import "./mode-families.test";
import "./facing.test";
import "./knaves.test";
import "./nested.test";
import "./graphdist.test";
import "./depth.test";
import "./construct.test";
import "./venn.test";
import "./maptable.test";
import "./combinations.test";
import "./width.test";
import "./display.test";
import "./timer.test";
import "./ungated.test";
import "./unlock.test";
import "./axis-map.test";
import "./widest-group.test";
import "./collapsible.test";
import "./hierarchy-syllogism.test";
import "./wide-premises.test";
import "./merge-schedule.test";
import "./reading-floor.test";
import "./recency.test";
import "./ceiling.test";
import "./flag-tristate.test";
import "./timer-bar.test";
import "./timer-budget.test";
import "./binary-halves.test";
import "./smooth-steps.test";
import "./share.test";
import "./concave-regions.test";
import "./concave-composition.test";
import "./index-imports.test";
import "./wide-card.test";
import "./mirror-twins.test";
import "./rcc8.test";
import "./context-cross.test";
import "./algebras.test";
import "./analogy-family.test";
import "./isomorphism.test";
import "./web-substructure.test";
import "./projection.test";
import "./mode-tag.test";
import "./goals.test";
import "./dials.test";
import "./player-sim.test";
import "./integration-load.test";
import "./minimal-coverage.test";
import "./rung-delivery.test";
import "./negation-count.test";
import "./build-map.test";
import "./registries.test";
import "./session.test";
import "./insight.test";
import "./series.test";
import "./testimony.test";
import "./deictic.test";
import "./anchor-negation.test";
import "./analogy-completion.test";
import "./dominance-ring.test";
import "./relation-systems.test";
import "./progress-dashboard.test";
import "./odd-analogy.test";
import "./interval-algebra.test";
import "./intervals.test";
import "./betweenness.test";
import "./mapping-conflict.test";
import "./contradiction.test";
import "./missing-premise.test";
import "./possibility.test";
import "./hidden-algebra.test";
import "./minimal-premises.test";

run();
