/* Generated by tools/fetch-pictures.mjs from list.json and Wikimedia Commons —
   do not edit; change list.json and let the workflow run. */
(function (root) {
  var PICTURES = [
   {
    "name": "apple",
    "image": "pictures/apple.jpg",
    "author": "Abhijit Tembhekar from Mumbai, India",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Red_Apple.jpg"
   },
   {
    "name": "banana",
    "image": "pictures/banana.jpg",
    "author": "Mohanramus",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SingleYelakki_banana,_bangalore,_karnataka_single.jpg"
   },
   {
    "name": "grapes",
    "image": "pictures/grapes.jpg",
    "author": "Ewan Munro from London, UK",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bunch_of_Grapes,_Brompton,_SW3_(4197149602).jpg"
   },
   {
    "name": "strawberry",
    "image": "pictures/strawberry.jpg",
    "author": "W.carter",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Still_life_with_strawberries_in_a_crystal_bowl.jpg"
   },
   {
    "name": "watermelon",
    "image": "pictures/watermelon.jpg",
    "author": "Ralff Nestor Nacor",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Watermelon_slice,_May_2024.jpg"
   },
   {
    "name": "lemon",
    "image": "pictures/lemon.jpg",
    "author": "André Karwath aka Aka",
    "licence": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Lemon.jpg"
   },
   {
    "name": "carrot",
    "image": "pictures/carrot.jpg",
    "author": "Stephen Ausmus",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Carrots_of_many_colors.jpg"
   },
   {
    "name": "corn",
    "image": "pictures/corn.jpg",
    "author": "Nutrition, Food Safety &amp; Health",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Corn_on_the_cob_(sweet_corn).jpg"
   },
   {
    "name": "mushroom",
    "image": "pictures/mushroom.jpg",
    "author": "George Chernilevsky",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Edible_fungi_in_basket_2012_G1.jpg"
   },
   {
    "name": "broccoli",
    "image": "pictures/broccoli.jpg",
    "author": "George Chernilevsky",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Romanesco_broccoli_2025_G2.jpg"
   },
   {
    "name": "cheese",
    "image": "pictures/cheese.jpg",
    "author": "Daderot",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Wedge_salad_with_blue_cheese_dressing_-_San_Francisco,_CA.jpg"
   },
   {
    "name": "pizza",
    "image": "pictures/pizza.jpg",
    "author": "Petar Milošević",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Vegetarian_Pizza.jpg"
   },
   {
    "name": "doughnut",
    "image": "pictures/doughnut.jpg",
    "author": "DoughnutEconomics",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Doughnut_(economic_model).jpg"
   },
   {
    "name": "cake",
    "image": "pictures/cake.jpg",
    "author": "Anna.Massini",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_birthday_cake!_Oops_there%27s_only_half_left!.jpg"
   },
   {
    "name": "dog",
    "image": "pictures/dog.jpg",
    "author": "Basile Morin",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Human%E2%80%93canine_friendship_-_girl_hugging_her_dog_tightly_at_golden_hour_in_Laos.jpg"
   },
   {
    "name": "cat",
    "image": "pictures/cat.jpg",
    "author": "Alvesgaspar",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cat_November_2010-1a.jpg"
   },
   {
    "name": "frog",
    "image": "pictures/frog.jpg",
    "author": "Bernard Spragg. NZ",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Green_and_Golden_Bell_Frog.jpg"
   },
   {
    "name": "pig",
    "image": "pictures/pig.jpg",
    "author": "Alvesgaspar",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pot-bellied_pigs_in_Lisbon_Zoo_2008.jpg"
   },
   {
    "name": "cow",
    "image": "pictures/cow.jpg",
    "author": "Kim Hansen",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cow_(Fleckvieh_breed)_Oeschinensee_Slaunger_2009-07-07.jpg"
   },
   {
    "name": "monkey",
    "image": "pictures/monkey.jpg",
    "author": "Thomas Schoch",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Macaque_India_3.jpg"
   },
   {
    "name": "chicken",
    "image": "pictures/chicken.jpg",
    "author": "Thegreenj",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hen_chicken.jpg"
   },
   {
    "name": "penguin",
    "image": "pictures/penguin.jpg",
    "author": "Sander Spek",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Sander-pinguins.jpg"
   },
   {
    "name": "lion",
    "image": "pictures/lion.jpg",
    "author": "Giles Laurent",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:002_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg"
   },
   {
    "name": "elephant",
    "image": "pictures/elephant.jpg",
    "author": "Charles J. Sharp",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:African_bush_elephants_(Loxodonta_africana)_female_with_six-week-old_baby.jpg"
   },
   {
    "name": "giraffe",
    "image": "pictures/giraffe.jpg",
    "author": "Byrdyak",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Three_giraffes_01.jpg"
   },
   {
    "name": "turtle",
    "image": "pictures/turtle.jpg",
    "author": "Moise Nicu",
    "licence": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tortoise_portrait.JPG"
   },
   {
    "name": "octopus",
    "image": "pictures/octopus.jpg",
    "author": "Comingio Merculiano (1845-1915) in Jatta Giuseppe (1860-1903)",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Octopus_vulgaris_Merculiano.jpg"
   },
   {
    "name": "butterfly",
    "image": "pictures/butterfly.jpg",
    "author": "Charles J. Sharp",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Common_brimstone_butterfly_(Gonepteryx_rhamni)_male.jpg"
   },
   {
    "name": "bee",
    "image": "pictures/bee.jpg",
    "author": "John Severns (Severnjc)",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg"
   },
   {
    "name": "fish",
    "image": "pictures/fish.jpg",
    "author": "Kritzolina",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Fountain_with_goldfish_in_Jard%C3%AD_del_Bisbe_03.jpg"
   },
   {
    "name": "car",
    "image": "pictures/car.jpg",
    "author": "Jebulon",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Red_car_toy.jpg"
   },
   {
    "name": "bicycle",
    "image": "pictures/bicycle.jpg",
    "author": "Basile Morin",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Parked_bicycle_with_graffitied_building_facade_and_doors_in_Amsterdam.jpg"
   },
   {
    "name": "aeroplane",
    "image": "pictures/aeroplane.jpg",
    "author": "Noah Wulf",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Airliner_Contrail.jpg"
   },
   {
    "name": "rocket",
    "image": "pictures/rocket.jpg",
    "author": "NASA",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:First_NASA_ISINGLASS_rocket_launch.jpg"
   },
   {
    "name": "sailboat",
    "image": "pictures/sailboat.jpg",
    "author": "Dietmar Rabich",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Zoutelande_(NL),_Strand,_Blick_auf_die_Nordsee_--_2022_--_4984.jpg"
   },
   {
    "name": "house",
    "image": "pictures/house.jpg",
    "author": "Arild Vågen",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ljungris_July_2013.jpg"
   },
   {
    "name": "alarm clock",
    "image": "pictures/alarm-clock.jpg",
    "author": "Santeri Viinamäki",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Classic_alarm_clock_20180513.jpg"
   },
   {
    "name": "key",
    "image": "pictures/key.jpg",
    "author": "The Metal Fest",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:MetalFestLogo2024.png"
   },
   {
    "name": "balloon",
    "image": "pictures/balloon.jpg",
    "author": "Kropsoq",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:2006_Ojiya_balloon_festival_011.jpg"
   },
   {
    "name": "guitar",
    "image": "pictures/guitar.jpg",
    "author": "Wilfredor",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Man_playing_an_acoustic_brazilian_guitar_(Viol%C3%A3o)_on_Marco_Zero_Square,_Refice,_Pernambuco,_Brazil.jpg"
   },
   {
    "name": "football",
    "image": "pictures/football.jpg",
    "author": "Jonathan McIntosh",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jakarta_old_football.jpg"
   },
   {
    "name": "hat",
    "image": "pictures/hat.jpg",
    "author": "Michael Evans",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Ronald_Reagan_with_cowboy_hat_12-0071M_edit.jpg"
   },
   {
    "name": "shoe",
    "image": "pictures/shoe.jpg",
    "author": "Petar Milošević",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Reebok_Royal_Glide_Ripple_Clip_shoe.jpg"
   },
   {
    "name": "umbrella",
    "image": "pictures/umbrella.jpg",
    "author": "Sopyaylynn",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Umbrella_Workshop.jpg"
   },
   {
    "name": "cactus",
    "image": "pictures/cactus.jpg",
    "author": "Tomascastelazo",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pachycereus_pringlei_forest.jpg"
   },
   {
    "name": "sunflower",
    "image": "pictures/sunflower.jpg",
    "author": "George Chernilevsky",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sunflower_head_2026_G1.jpg"
   },
   {
    "name": "moon",
    "image": "pictures/moon.jpg",
    "author": "Luc Viatour",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Full_Moon_Luc_Viatour.jpg"
   },
   {
    "name": "candle",
    "image": "pictures/candle.jpg",
    "author": "W.carter",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Candle_light_projected_through_a_glass_orb.jpg"
   },
   {
    "name": "fire",
    "image": "pictures/fire.jpg",
    "author": "kallerna",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Campfire_and_sparks_in_Anttoora_3.jpg"
   },
   {
    "name": "rainbow",
    "image": "pictures/rainbow.jpg",
    "author": "Wing-Chi Poon",
    "licence": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:WhereRainbowRises.jpg"
   },
   {
    "name": "snowman",
    "image": "pictures/snowman.jpg",
    "author": "Sphiiix",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bonhomme_de_neige_2.jpg"
   },
   {
    "name": "light bulb",
    "image": "pictures/light-bulb.jpg",
    "author": "KMJ",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gluehlampe_01_KMJ.jpg"
   },
   {
    "name": "books",
    "image": "pictures/books.jpg",
    "author": "mycurrency.com",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Stack_of_Books_for_decor.jpg"
   },
   {
    "name": "scissors",
    "image": "pictures/scissors.jpg",
    "author": "Crisco 1492",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pair_of_scissors_with_black_handle,_2015-06-07.jpg"
   },
   {
    "name": "bell",
    "image": "pictures/bell.jpg",
    "author": "Dmitry A. Mottl",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chersonesos_Bell.jpg"
   },
   {
    "name": "teapot",
    "image": "pictures/teapot.jpg",
    "author": "George Chernilevsky",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Teapot_2010_G1.jpg"
   }
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = PICTURES;
  else root.RunningOrderPictures = PICTURES;
})(this);
