/* Generated by tools/fetch-pictures.mjs from list.json and Wikimedia Commons —
   do not edit; change list.json and let the workflow run. */
(function (root) {
  var PICTURES = [
   {
    "name": "apple",
    "image": "pictures/apple.jpg",
    "author": "Abhijit Tembhekar from Mumbai, India",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Red_Apple.jpg"
   },
   {
    "name": "banana",
    "image": "pictures/banana.jpg",
    "author": "Mohanramus",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SingleYelakki_banana,_bangalore,_karnataka_single.jpg"
   },
   {
    "name": "pear",
    "image": "pictures/pear.jpg",
    "author": "Rhododendrites",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:D%27anjou_pear.jpg"
   },
   {
    "name": "strawberry",
    "image": "pictures/strawberry.jpg",
    "author": "W.carter",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Still_life_with_strawberries_in_a_crystal_bowl.jpg"
   },
   {
    "name": "watermelon",
    "image": "pictures/watermelon.jpg",
    "author": "Ralff Nestor Nacor",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Watermelon_slice,_May_2024.jpg"
   },
   {
    "name": "lemon",
    "image": "pictures/lemon.jpg",
    "author": "André Karwath aka Aka",
    "licence": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Lemon.jpg"
   },
   {
    "name": "sheep",
    "image": "pictures/sheep.jpg",
    "author": "User:Diliff",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Swaledale_Sheep,_Lake_District,_England_-_June_2009.jpg"
   },
   {
    "name": "corn",
    "image": "pictures/corn.jpg",
    "author": "Nutrition, Food Safety &amp; Health",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Corn_on_the_cob_(sweet_corn).jpg"
   },
   {
    "name": "mushroom",
    "image": "pictures/mushroom.jpg",
    "author": "George Chernilevsky",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Edible_fungi_in_basket_2012_G1.jpg"
   },
   {
    "name": "broccoli",
    "image": "pictures/broccoli.jpg",
    "author": "HaJunkiyada",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Broccoli_from_San_Francisco_farmers_market.jpg"
   },
   {
    "name": "cheese",
    "image": "pictures/cheese.jpg",
    "author": "Frank Schulenburg",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cowgirl_Creamery_Point_Reyes_-_Red_Hawk_cheese.jpg"
   },
   {
    "name": "pizza",
    "image": "pictures/pizza.jpg",
    "author": "Mario56",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG"
   },
   {
    "name": "doughnut",
    "image": "pictures/doughnut.jpg",
    "author": "Evan-Amos",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Dough-Doughnut-Blood-Orange.jpg"
   },
   {
    "name": "cake",
    "image": "pictures/cake.jpg",
    "author": "Francesca Cesa Bianchi, Milano",
    "licence": "CC BY-SA 3.0 it",
    "source": "https://commons.wikimedia.org/wiki/File:Italy_-_birthday_cake_with_candles_5.jpg"
   },
   {
    "name": "dog",
    "image": "pictures/dog.jpg",
    "author": "Dietmar Rabich",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Hausd%C3%BClmen,_Golden_Retriever_--_2022_--_5945.jpg"
   },
   {
    "name": "cat",
    "image": "pictures/cat.jpg",
    "author": "Alvesgaspar",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cat_November_2010-1a.jpg"
   },
   {
    "name": "frog",
    "image": "pictures/frog.jpg",
    "author": "Bernard Spragg. NZ",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:The_Green_and_Golden_Bell_Frog.jpg"
   },
   {
    "name": "pig",
    "image": "pictures/pig.jpg",
    "author": "Alvesgaspar",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pot-bellied_pigs_in_Lisbon_Zoo_2008.jpg"
   },
   {
    "name": "cow",
    "image": "pictures/cow.jpg",
    "author": "Kim Hansen",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cow_(Fleckvieh_breed)_Oeschinensee_Slaunger_2009-07-07.jpg"
   },
   {
    "name": "monkey",
    "image": "pictures/monkey.jpg",
    "author": "Thomas Schoch",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Macaque_India_3.jpg"
   },
   {
    "name": "chicken",
    "image": "pictures/chicken.jpg",
    "author": "Thegreenj",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hen_chicken.jpg"
   },
   {
    "name": "penguin",
    "image": "pictures/penguin.jpg",
    "author": "Sander Spek",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Sander-pinguins.jpg"
   },
   {
    "name": "lion",
    "image": "pictures/lion.jpg",
    "author": "Giles Laurent",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:002_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg"
   },
   {
    "name": "elephant",
    "image": "pictures/elephant.jpg",
    "author": "Charles J. Sharp",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:African_bush_elephants_(Loxodonta_africana)_female_with_six-week-old_baby.jpg"
   },
   {
    "name": "giraffe",
    "image": "pictures/giraffe.jpg",
    "author": "Byrdyak",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Three_giraffes_01.jpg"
   },
   {
    "name": "turtle",
    "image": "pictures/turtle.jpg",
    "author": "Moise Nicu",
    "licence": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tortoise_portrait.JPG"
   },
   {
    "name": "octopus",
    "image": "pictures/octopus.jpg",
    "author": "Comingio Merculiano (1845-1915) in Jatta Giuseppe (1860-1903)",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Octopus_vulgaris_Merculiano.jpg"
   },
   {
    "name": "butterfly",
    "image": "pictures/butterfly.jpg",
    "author": "Charles J. Sharp",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Common_brimstone_butterfly_(Gonepteryx_rhamni)_male.jpg"
   },
   {
    "name": "bee",
    "image": "pictures/bee.jpg",
    "author": "John Severns (Severnjc)",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg"
   },
   {
    "name": "fish",
    "image": "pictures/fish.jpg",
    "author": "Nick Hobgood",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Amphiprion_ocellaris_(Clown_anemonefish)_by_Nick_Hobgood.jpg"
   },
   {
    "name": "car",
    "image": "pictures/car.jpg",
    "author": "Matti Blume",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:VW_Golf_R,_Berlin_(1X7A3939).jpg"
   },
   {
    "name": "bicycle",
    "image": "pictures/bicycle.jpg",
    "author": "Petar Milošević",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dutch_bicycle.jpg"
   },
   {
    "name": "aeroplane",
    "image": "pictures/aeroplane.jpg",
    "author": "Julian Herzog (Website)",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lufthansa_Airbus_A320-211_D-AIQT_01.jpg"
   },
   {
    "name": "rocket",
    "image": "pictures/rocket.jpg",
    "author": "NASA",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Space_Shuttle_Columbia_launching.jpg"
   },
   {
    "name": "sailboat",
    "image": "pictures/sailboat.jpg",
    "author": "Dietmar Rabich",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Zoutelande_(NL),_Strand,_Blick_auf_die_Nordsee_--_2022_--_4984.jpg"
   },
   {
    "name": "house",
    "image": "pictures/house.jpg",
    "author": "Arild Vågen",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ljungris_July_2013.jpg"
   },
   {
    "name": "alarm clock",
    "image": "pictures/alarm-clock.jpg",
    "author": "Santeri Viinamäki",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Classic_alarm_clock_20180513.jpg"
   },
   {
    "name": "owl",
    "image": "pictures/owl.jpg",
    "author": "Rhododendrites",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Eurasian_eagle-owl_(44088).jpg"
   },
   {
    "name": "balloon",
    "image": "pictures/balloon.jpg",
    "author": "Kropsoq",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:2006_Ojiya_balloon_festival_011.jpg"
   },
   {
    "name": "guitar",
    "image": "pictures/guitar.jpg",
    "author": "Wilfredor",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Paramount_Series_acoustic_guitars.jpg"
   },
   {
    "name": "football",
    "image": "pictures/football.jpg",
    "author": "Peter Glaser baraida",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Adidas_soccer_ball_on_a_grass_pitch_(Unsplash).jpg"
   },
   {
    "name": "zebra",
    "image": "pictures/zebra.jpg",
    "author": "Yathin S Krishnappa",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Equus_zebra_hartmannae_-_Etosha_2015.jpg"
   },
   {
    "name": "shoe",
    "image": "pictures/shoe.jpg",
    "author": "Petar Milošević",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Reebok_Royal_Glide_Ripple_Clip_shoe.jpg"
   },
   {
    "name": "horse",
    "image": "pictures/horse.jpg",
    "author": "Alvesgaspar",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Horse_December_2014-1.jpg"
   },
   {
    "name": "cactus",
    "image": "pictures/cactus.jpg",
    "author": "Tomascastelazo",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pachycereus_pringlei_forest.jpg"
   },
   {
    "name": "sunflower",
    "image": "pictures/sunflower.jpg",
    "author": "George Chernilevsky",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sunflower_head_2026_G1.jpg"
   },
   {
    "name": "moon",
    "image": "pictures/moon.jpg",
    "author": "Luc Viatour",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Full_Moon_Luc_Viatour.jpg"
   },
   {
    "name": "candle",
    "image": "pictures/candle.jpg",
    "author": "Petar Milošević",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Candle_(Slava_celebration).jpg"
   },
   {
    "name": "fire",
    "image": "pictures/fire.jpg",
    "author": "Marc-Lautenbacher",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Campfire_flames_at_night.jpg"
   },
   {
    "name": "rainbow",
    "image": "pictures/rainbow.jpg",
    "author": "Wing-Chi Poon",
    "licence": "CC BY-SA 2.5",
    "source": "https://commons.wikimedia.org/wiki/File:WhereRainbowRises.jpg"
   },
   {
    "name": "snowman",
    "image": "pictures/snowman.jpg",
    "author": "Sphiiix",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bonhomme_de_neige_2.jpg"
   },
   {
    "name": "light bulb",
    "image": "pictures/light-bulb.jpg",
    "author": "KMJ",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gluehlampe_01_KMJ.jpg"
   },
   {
    "name": "books",
    "image": "pictures/books.jpg",
    "author": "Roman Eisele",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Part_of_a_bookshelf_containing_books_by_Aristotle_(1).jpg"
   },
   {
    "name": "scissors",
    "image": "pictures/scissors.jpg",
    "author": "Crisco 1492",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Pair_of_scissors_with_black_handle,_2015-06-07.jpg"
   },
   {
    "name": "hedgehog",
    "image": "pictures/hedgehog.jpg",
    "author": "George Chernilevsky",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Erinaceus_roumanicus_2020_G2.jpg"
   },
   {
    "name": "teapot",
    "image": "pictures/teapot.jpg",
    "author": "George Chernilevsky",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Teapot_2010_G1.jpg"
   }
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = PICTURES;
  else root.RunningOrderPictures = PICTURES;
})(this);
